# Copyright (C) 2009  Rickard Lindberg, Roger Lindberg
#
# This file is part of Timeline.
#
# Timeline is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Timeline is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Timeline.  If not, see <http://www.gnu.org/licenses/>.

Import("env")

env.Alias("pot", env.Pot("timeline.pot", Glob("../src/*.py")))

language_map = {"sv": "sv_SE"}
for key, value in language_map.items():
    target = "%s/LC_MESSAGES/timeline.mo" % value
    env.Alias("mo", env.Mo(target, "%s.po" % key))
    env.Clean(target, value)
