# Copyright (C) 2009  Rickard Lindberg, Roger Lindberg
#
# This file is part of Timeline.
#
# Timeline is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Timeline is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Timeline.  If not, see <http://www.gnu.org/licenses/>.

Import("env")

if not env["XGETTEXT"]:
    print("WARNING: pot target disabled because xgettext was not found")
else:
    flags = " --copyright-holder=\"Rickard Lindberg\"" \
            " --package-name=Timeline" \
            " --package-version=0.4.0"
    env.Alias("pot", env.Pot("timeline.pot", Glob("../src/*.py"),
                             XGETTEXTFLAGS=flags))

if not env["MSGFMT"]:
    print("WARNING: mo target disabled because msgfmt was not found")
else:
    languages = ["sv", "es", "de", "pt_BR", "pt"]
    for language in languages:
        target = "%s/LC_MESSAGES/timeline.mo" % language
        env.Alias("mo", env.Mo(target, "%s.po" % language))
        env.Clean(target, language) # Removed the folder

# vim: syntax=python
