#!/bin/sh

DEB_TARGET_DIR=`pwd`
THIS_DIR=`dirname $0`
SOURCE_DIR=`readlink -m $THIS_DIR/../..`
VERSION=`python $SOURCE_DIR/timeline.py --version | awk '{print $2}'`
SOURCE_DIR_NAME=`basename "$SOURCE_DIR"`
DEBIAN_DIR=`dirname $0`/debian
TMP_DIR=`mktemp -d`
CHANGELOG="$TMP_DIR/$SOURCE_DIR_NAME/debian/changelog"

cp -r "$SOURCE_DIR" "$TMP_DIR"
cp -r "$DEBIAN_DIR" "$TMP_DIR/$SOURCE_DIR_NAME"

(
cat > "$CHANGELOG" << END
timeline ($VERSION-1) unstable; urgency=low

  * New upstream release.

 -- Rickard Lindberg <ricli85@gmail.com>  `date -R`

END
cd "$TMP_DIR/$SOURCE_DIR_NAME" &&
dpkg-buildpackage -B -uc -tc -rfakeroot &&
mv "$TMP_DIR/timeline_$VERSION-1_all.deb" "$DEB_TARGET_DIR"
)

build_exit_code=$?

rm -r $TMP_DIR

exit $build_exit_code
