#!/bin/sh

REPO_ROOT="http://thetimelineproj.hg.sourceforge.net:8000/hgroot/thetimelineproj"
REPO=$REPO_ROOT/$1
TMP=`mktemp -d`

(
hg clone $REPO $TMP/repo &&
./test $TMP/repo 0.0.0
)

exit_code=$?

rm -r $TMP

exit $exit_code
