#!/bin/sh

THIS_DIR=`dirname $0`
SOURCE_DIR=`readlink -m $THIS_DIR/../..`
VERSION=`python $SOURCE_DIR/timeline.py --version | awk '{print $2}'`
DEB_FILE="timeline_$VERSION-1_all.deb"
LIB_INSTALL_PATH="/usr/lib/timeline/timelinelib"
SRC_LIB=$SOURCE_DIR/timelinelib
SRC_LIB_BACKUP=$SOURCE_DIR/timelinelib_old

(
$THIS_DIR/build &&
su -c "dpkg -i $DEB_FILE" &&
rm $DEB_FILE &&

mv "$SRC_LIB" "$SRC_LIB_BACKUP" &&
ln -s "$LIB_INSTALL_PATH" "$SRC_LIB" &&
"$SOURCE_DIR/execute-specs.py" &&
rm "$SRC_LIB" &&
mv "$SRC_LIB_BACKUP" "$SRC_LIB"
)

spec_exit_code=$?

su -c "apt-get --assume-yes remove timeline"

exit $spec_exit_code
